version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: employee-system-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
  redis:
    image: redis:alpine
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  postgres_data:

networks:
  default:
    driver: bridge